jenkins_server: http://localhost:8080/
builds:
  - name: random_number_generator
    parameters:
      LIMIT: 10
  - name: random_number_generator
    parameters:
      LIMIT: abc1000
  - name: nonexistent_job
    parameters:
      LIMIT: 100
  - name: random_number_generator
    parameters:
      LIMIT: 100
