jenkins_server: http://localhost:8080/
builds:
  - name: random_number
    parameters:
      number: 12
  - name: random_number
    parameters:
      number: 123
  - name: random_numer
    parameters:
      number: 1234
  - name: random_number
    parameters:
      number: 12345
